### ISSUE TITLE
似乎无弹跳高度限制

### ISSUE THREAD

**Issue by poppinlp** [fireball-x/game-duang-sheep#11]
来自官网DEMO，不知现在修复没有。
绵羊无弹跳高度限制，于是只需要一直点击鼠标即可一直走。

**Comment by jwu** [comment]
这个 demo 是 0.4 版本时我们做来测试实际案例的. 目前 Fireball 正在进行 0.5 版本的重构, 由于和 0.4 版本相比有着巨大的改变, 所以我们会为 0.5 版本做新的 demo 案例. 请耐心等待.
